import turtle 
turtle.Screen ().bgcolor ("blue")
triangle = turtle.Turtle ()
triangle.forward (100)
triangle.left (120)
triangle.forward (100)
triangle.left (120)
triangle.forward (100)
triangle.right (150)
triangle.penup ()
triangle.forward (50)
triangle.right (90)
triangle.pendown ()
triangle.forward (100)
triangle.right (120)
triangle.forward (100)
triangle.right (120)
triangle.forward (100)
turtle. done ()
